logger:
  level: info
team:
  formation: 3-3
  shirt: home
  name: team_a
sprites_path: src/client/sprites
init_mode: client
server_hostname: localhost
users:
  - name: user
    password: 1234
  - name: user2
    password: 1234
